language: clojure
sudo: required
lein: 2.7.1

env:
- MYSQL_ROOT_PASSWORD: "sogeti"
- MYSQL_DATABASE: "sogeti_d"

services:
- docker

before_install:
  - docker-compose up database
  - sleep 15
  - mysqladmin -h 127.0.0.1 --count=5 --sleep=2 ping
  - mysql -h 127.0.0.1 -e 'SHOW DATABASES;'

script:
- lein test

jdk:
- openjdk7
