language: clojure
sudo: required
lein: 2.7.1

test:
  adapter: mysql2
  database: myapp_test
  username: root
  encoding: utf8

services:
- mysql
#- docker

#install:
#  - sudo rm -Rf /var/lib/apt/lists/*
#  - sudo apt-get update -qq
#  - sudo apt-get install -y mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6

#script:
#- lein test

#jdk:
#- openjdk7
