language: clojure
lein: 2.7.1

sudo: required

env: ENV=travis DATABASE_NAME=sogeti_d DATABASE_USER=sogeti_u DATABASE_HOST=127.0.0.1 DATABASE_PASSWORD=sogeti

services:
- mysql

before_script:
- lein deps
- lein with-profile travis migrate

script:
- lein with-profile travis test

jdk:
- openjdk7
