language: clojure
lein: 2.7.1

sudo: required

env: ENV=docker DATABASE_NAME=sogeti_d DATABASE_USER=sogeti_u DATABASE_HOST=127.0.0.1 DATABASE_PASSWORD=sogeti

services:
- docker

before_script:
- docker ps -a
- netstat -alnp | grep 3306
- sudo /etc/init.d/mysql stop
- docker-compose up -d
- lein deps
- lein with-profile docker migrate

script:
- lein with-profile docker test

