sudo: required

services:
- docker

before_script:
- docker ps -a
- netstat -alnp | grep 3306
- sudo /etc/init.d/mysql stop
- docker-compose up -d
- lein deps
- lein with-profile docker migrate

script:
- lein with-profile docker test

