language: clojure
sudo: required
lein: 2.7.1

env:
- MYSQL_ROOT_PASSWORD: "sogeti"
- MYSQL_DATABASE: "sogeti_d"

services:
- mysql
- docker

install:
  - sudo rm -Rf /var/lib/apt/lists/*
  - sudo apt-get update -qq
  - sudo apt-get install -y mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6

script:
- lein test

jdk:
- openjdk7
