sudo: required

services:
- docker

before_script:
- sudo /etc/init.d/mysql stop
- docker-compose up -d
- lein deps
- lein with-profile docker migrate

script:
- lein with-profile docker test

after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

