language: clojure
lein: 2.7.1

env:
- MYSQL_ROOT_PASSWORD: "sogeti"
- MYSQL_DATABASE: "sogeti_d"
- MYSQL_ROOT_PASSWORD_UPDATE: yes

services:
- mysql

before_script:
- lein deps
- lein with-profile travis migrate

script:
- lein with-profile travis test

jdk:
- openjdk7
